sonata_admin:
    title: 'LiveGene'
    title_logo: 'http://azizi.ilri.org/livegene_admin/logo.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_stylesheets:
            - build/app.css
        extra_javascripts:
            - build/app.js
    security:
        handler: sonata.admin.security.handler.role

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
