sonata_media_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#sonata_media_api:
#    resource: "@SonataMediaBundle/Resources/config/routing/api.xml"
#    prefix: /api
#    type: annotation
